wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1670039263.558347
    t:
      1:
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.5
      8:
      - 4
      - 5
