wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669950854
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      3:
      - 3
      - 8
      - 19
      - 24
      4: 3.9.13
      5: 0.12.19
      8:
      - 4
      - 5
      10:
      - 9
magic:
  desc: null
  value:
    enable: true
