wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669950192
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 3
      - 8
      - 19
      - 24
      4: 3.9.13
      5: 0.12.19
      8:
      - 4
      - 5
      10:
      - 9
    visualize:
      accuracy_missingness_plot:
        panel_config:
          fieldSettings:
            stroke: null
            x: Percent Observed
            y: Accuracy
          panelDefId: wandb/line/v0
          stringSettings:
            title: Accuracy vs. Missingness
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: accuracy_missingness_plot_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
dataset:
  desc: null
  value: retina
epochs:
  desc: null
  value: '5'
magic:
  desc: null
  value:
    enable: true
